### PR TITLE
Some modifications for Linux compatibility.

### PR DESCRIPTION
**Pull request by fredvs**

### CODE REVIEW

**Comment by fredvs** [comment]
Hello Roland.

Félicitations pour votre premier projet GitHub!
Je continue en Anglais pour qu'on nous comprenne.

I have to change line 91 of validator.pas:
  
s := e.Replace(s, ExpandEmptySquares());

changed with

s := e.Replace(s, @ExpandEmptySquares);

I do not understand why, it is not Linux related, but otherwise it does not compile here.

Also added moustique.prj for MSEgui/ideU users.

Otherwise, Moustique seems Unix ready.

Fre;D

**Comment by rchastain** [comment]
Hello Fred!
Merci beaucoup pour votre contribution.
Maybe the explanation is that I use the Delphi mode.
Best regards.
Roland

**Comment by JonnyTech** [comment]
Why so many changes? It is good practice to keep the diffs as short and clean as possible in order to find what was changed quickly and easily. This diff has 4 changed files with 1527 additions and 236 deletions!

**Comment by fredvs** [comment]
Hello Jonny.

Are you taking of my pull-request ?
Yes, IMHO, git should only note as diff one line inserted, line 5 of moustique.pas:
`{$mode objfpc}{$H+}`

But Git consider as changed all the lines offset because of that insertion!

Fre;D

**Comment by rchastain** [comment]
Hello! Maybe it is the problem with line endings (see Martin message in fpGUI news)?

 

Regards.

 

Roland

 

Envoyé: dimanche 11 novembre 2018 à 13:51
De: "Fred van Stappen" <notifications@github.com>
À: rchastain/moustique <moustique@noreply.github.com>
Cc: "Roland Chastain" <roland.chastain@gmx.fr>, "State change" <state_change@noreply.github.com>
Objet: Re: [rchastain/moustique] Some modifications for Linux compatibility. (#1)


Hello Jonny.

Are you taking of my pull-request ?
Yes, IMHO, git should only notr that one line was inserted.
But Git consider as changed all the lines offset because of that insertion!

Fre;D

**Pull request merged**
